services:
  paic:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    image: ghcr.io/mareox/egress-ip-condenser:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./profiles:/app/profiles
